name: labograttoir.photos
favicon: null
layout_spectrum: 0.48747
typography_spectrum: 0.45242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d5d5d7'
    - '#1f1f1f'
    - '#9e9993'
    - '#544d49'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
