typography_spectrum: 0.45242
color:
  brandColors:
    - '#ffffff'
    - '#d5d5d7'
    - '#1f1f1f'
    - '#9e9993'
    - '#544d49'
  brandStrength: 0.9375
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48747
analytics:
  google: null
  facebook: null
  twitter: null
name: labograttoir.photos
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: OPUS
purpose: []
