name: labograttoir.photos
favicon: null
layout_spectrum: 0.11434
typography_spectrum: 0.82137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2f2d44'
    - '#130c1e'
    - '#768eba'
    - '#59607a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
