layout_spectrum: 0.09005196508951485
typography_spectrum: 0.6997338954824954
color:
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  brandStrength: 0.29202075744979084
  lightness: 0.12387804896570742
  saturation: 0.471757436869666
  rhythmicContrast: 0.7944254889152944
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: labograttoir.photos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: BERLIN
    id: b9dcc9a9-308b-4a6e-b12b-2f21b5ac302f
    type: content
  - name: Vercors
    id: af0a0995-60ce-4ea3-afa0-2023ff4aaf91
    type: content
  - name: 'reserve '
    id: 9e3b4692-960f-4078-ad9c-99a49fd34374
    type: content
  - name: glissart
    id: 624c54f8-93ce-433c-a621-06b16860d3bb
    type: content
favicon: null
title: HORI_ZONE
description: OPUS I
purpose: []
