name: labograttoir.photos
favicon: null
layout_spectrum: 0.66777
typography_spectrum: 0.82137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5bf90'
    - '#010200'
    - '#ecf8e0'
    - '#313f48'
    - '#d85402'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
