name: labograttoir.photos
favicon: null
layout_spectrum: 0.73705
typography_spectrum: 0.8197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9c6a6'
    - '#6a492a'
    - '#281203'
    - '#a28961'
    - '#4f8ca1'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
