typography_spectrum: 0.751596869667992
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.27100726729258895
  lightness: 0.26635179622098804
  saturation: 0.22376367752440274
  rhythmicContrast: 0.3738126754760742
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48747
analytics:
  google: null
  facebook: null
  twitter: null
name: labograttoir.photos
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: BERLIN
    id: b9dcc9a9-308b-4a6e-b12b-2f21b5ac302f
    type: content
favicon: null
title: HORI_ZONE
description: OPUS I
purpose: []
