name: labograttoir.photos
favicon: null
layout_spectrum: 0.70147
typography_spectrum: 0.79869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4f6071'
    - '#010101'
    - '#afb2bb'
    - '#98774a'
  brandStrength: 0.5625
  lightness: 0.7710905123967677
  saturation: 0.5625
  rhythmicContrast: 0.3474861413706094
purpose: []
