name: labograttoir.photos
favicon: null
layout_spectrum: 0.48747
typography_spectrum: 0.45242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5bf90'
    - '#010200'
    - '#ecf8e0'
    - '#313f48'
    - '#d85402'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
